

FROM mariadb:latest

LABEL version="1.0"
LABEL description="Votação do BBB - Database"

ENV MYSQL_ROOT_PASSWORD "p4r3d40bbb_r0ot_pr0d"

ENV MYSQL_DATABASE "paredao_bbb"
ENV MYSQL_USER "paredao_bbb"
ENV MYSQL_PASSWORD "p4r3d40_bbb_aleuck!"

EXPOSE 3306

CMD ["mysqld"]
